### PR TITLE
Add Restart Button for containers

### PR DESCRIPTION
**Pull request by briodan**
I found it handy to have a restart button for containers that I can push from a dashboard.

### CODE REVIEW

**Comment by briodan** [comment]
moved the button to asyncio based on the work in PR #140

**Comment by ualex73** [comment]
I am happy to merge this one, but can you put the default too disable for this button feature? I think most users will not prefer it, if even more entities are added to HA.

So change:
vol.Optional(CONF_BUTTONENABLED, default=True): vol.Any(
to:
vol.Optional(CONF_BUTTONENABLED, default=False): vol.Any(

**Comment by briodan** [comment]
my use case is to have an auto entities card that auto-populates with the reboot buttons for all containers, that way as i add/remove containers the reboot button automatically shows up and i don't have to manage it.

maybe this can be added as a configuration option, so the button is disabled by default but can be enabled by default if the user choses it, but that might be to big of a code change. Can probably achieve that with an automation of sorts.

**Comment by ualex73** [comment]
I just merged the change in the master.

**Pull request merged**
